memory_limit = 512M
max_execution_time = 0
date.timezone = America/Sao_Paulo

opcache.enable = 1
opcache.enable_cli = 0
opcache.memory_consumption = 128
opcache.max_accelerated_files = 20000
opcache.validate_timestamps = 1
opcache.revalidate_freq = 2
